version: '3'
services:
  rservice:
    image: r-base:4.3.1
    volumes:
      - /Users/boyie/Dropbox/boyie_dropbox/external_share/version_control_examples:/dropbox
      - ./scripts:/scripts
    entrypoint: ["/bin/bash", "-c", "/scripts/setup.sh && /bin/bash"]

  rstudio:
    image: rocker/rstudio:4.3
    ports:
      - 8787:8787
    environment:
      PASSWORD : rstudio
      ROOT : TRUE
    volumes:
      - ./.rstudio_config:/home/rstudio/.config/rstudio
      - ~/workspace:/home/rstudio/workspace
      - ./scripts:/home/rstudio/workspace/scripts
      - /Users/boyie/Dropbox/boyie_dropbox/external_share/version_control_examples:/dropbox